### PR TITLE
GEO-47 client failing to reconnect to es after timeout

### PR DESCRIPTION
**Pull request by alenkalac**
Added retry mechanism to fix the ES timing out issue - when the client times out, it will retry upto 3 times before it throws the error back to the importer.

### CODE REVIEW

**Comment by ainemitch** [comment]
Hey Alen could you update the start script with the memory requirements needed for the world import?
I tried 8 and 10GB but it ran out of memory with both of those. 

exec node --max_old_space_size=6000 import.js

Cheers

**Comment by alenkalac** [comment]
> Hey Alen could you update the start script with the memory requirements needed for the world import?
> I tried 8 and 10GB but it ran out of memory with both of those.
> 
> exec node --max_old_space_size=6000 import.js
> 
> Cheers

Hi Aine, I am currently importing the whole world, Max memory usage I have seen so far used by node.js is about 17GB at one time. 

I have allocated 25GB to the heapspace and running for for over an hour without any issues. 
Once this is done, i'll reduce it to 20GB and try again until I get to a point where it breaks and will update this thread once I get the numbers. :) 

thanks for the comment!

**Comment by alenkalac** [comment]
> Hey Alen could you update the start script with the memory requirements needed for the world import?
> I tried 8 and 10GB but it ran out of memory with both of those.
> 
> exec node --max_old_space_size=6000 import.js
> 
> Cheers

HI Aine, I have updated the script, I was able to import the whole world with about 13GB of ram allocation, I added an extra gig for buffer.

after whole planet import: 4.7mil documents in ES. 

Thanks :)

**Review by tomislavkosutic — APPROVED** [review]

**Comment by ainemitch** [comment]
Cheers for that Alen looks good there.

**Review by ainemitch — APPROVED** [review]

**Pull request merged**
